version: "3.8"
services:
  app:
    container_name: ngcxstaging
    image: ngcxstaging
    build:
      context: .
      dockerfile: Dockerfile.stage
    ports:
      - 80:80
    environment:
      - NODE_ENV=development
      - PORT=80

      
