version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
  deploy-dev:
    docker:
        - image: circleci/node:14
    steps:
      - checkout
      # install dependencies and run terraform commands to send image to aws and stage code
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run:
          name: build and push docker image to heroku
          command: yarn test

workflows:
  version: 2
  ngcx_deploy:
    jobs:
      - build
      - deploy-dev: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master 